### ISSUE TITLE
Missing talks

### ISSUE THREAD

**Issue by maelle** [jimhester/jimhester.com#3]
The talks page seems empty at the moment https://www.jimhester.com/talks/ (I noticed because I lazily looked there to find https://speakerdeck.com/jimhester/github-actions-for-r).

**Comment by jimhester** [comment]
Thanks, not sure what happened, I added the talk and pushed again, I will check tomorrow to make sure the CRON build did not revert things...

**Comment by maelle** [comment]
Awesome! I was thinking maybe the Hugo version was the problem? Why not set a specific Hugo version in

https://github.com/jimhester/jimhester.com/blob/bfc4b656c09a4dda4184139363d0644f635e5e5b/.github/workflows/main.yml#L29

?

**Comment by maelle** [comment]
(and yay for being able to find the talk via your website :tada: )

**Comment by jimhester** [comment]
No reason, I don't think I even knew you could specify the version of hugo in `install_hugo()`!

**Comment by maelle** [comment]
I actually [looked into such things two days ago](https://masalmon.eu/2020/02/29/hugo-maintenance/#don-t-live-on-the-edge) :slightly_smiling_face:

**Comment by maelle** [comment]
(which is when I saw that function argument)

**Comment by maelle** [comment]
The page is empty again, as I saw when wanting to link to the GH Actions page :cry:

**Comment by jimhester** [comment]
It looks like that is because you can't install a specific version if using homebrew (which is the default) https://github.com/jimhester/jimhester.com/runs/480965085?check_suite_focus=true#step:8:220

I just changed the workflow to not use homebrew, so hopefully it will be fixed 🤞

**Comment by maelle** [comment]
Interesting! :four_leaf_clover:
